name: mcquenji_local_storage
description: "Module for storing data locally on the device."
version: 0.0.1
homepage: https://github.com/mcquenji/mcquenji_local_storage
publish_to: none # Remove this line if you wish to publish to pub.dev
platforms:
  web:
  windows:
  linux:
  macos:

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.1.4
  collection: ^1.18.0
  crypto: ^3.0.3
  either_dart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_modular: ^6.3.4
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  mcquenji_core:
    git:
      url: https://github.com/mcquenji/mcquenji_core.git
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  universal_html: ^2.2.4
  universal_io: ^2.2.2

dev_dependencies:
  architecture_linter: ^0.2.2
  build_runner: ^2.4.11
  flutter_gen: ^5.6.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  flutterando_analysis: ^0.0.2
  freezed: ^2.5.2
  json_serializable: ^6.8.0
